# Generated by Django 6.0 on 2025-12-19 18:35

import accounts.validations.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_users_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="national_code",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    accounts.validations.validations.is_valid_iranian_national_code
                ],
                verbose_name="National Code",
            ),
        ),
    ]
